import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';
import{LocalProfiles}from'../src/local-services.js';import{newSave}from'../src/model.js';
import{persistOriginalProfile}from'../src/original-save.js';import{ORIGINAL_OPTIONS_KEY,readOriginalOptions,writeOriginalOptions,installOriginalOptions}from'../src/original-options.js';
const data=JSON.parse(readFileSync(new URL('../public/data/game-data.json',import.meta.url)));
function fixture(request){const values=new Map(),storage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)},save=newSave(data,1),profiles=new LocalProfiles(data,storage,request);profiles.bank={version:1,active:0,slots:[save,null,null],updatedAt:''};return{storage,save,profiles};}
test('source Save waits for the local disk acknowledgment',async()=>{let release,requested=false;const f=fixture(async()=>{requested=true;await new Promise(resolve=>release=resolve);return{ok:true,json:async()=>({revision:7})};});f.profiles.serverAvailable=true;let complete=false;const save=persistOriginalProfile(f.profiles,f.save).then(v=>{complete=true;return v;});while(!requested)await Promise.resolve();assert.equal(complete,false);release();assert.deepEqual(await save,{destination:'disk'});assert.equal(f.profiles.serverRevision,7);});
test('source Save can succeed in static browser storage and catches storage failure',async()=>{const f=fixture();assert.deepEqual(await persistOriginalProfile(f.profiles,f.save),{destination:'browser'});f.storage.setItem=()=>{throw new Error('Storage full');};await assert.rejects(persistOriginalProfile(f.profiles,f.save),/Storage full/);});
test('disk failure selects source retry state and a successful retry can recover',async()=>{let fail=true;const f=fixture(async()=>fail?{ok:false,status:503}:{ok:true,json:async()=>({revision:3})});f.profiles.serverAvailable=true;await assert.rejects(persistOriginalProfile(f.profiles,f.save),/could not save/);fail=false;assert.deepEqual(await persistOriginalProfile(f.profiles,f.save),{destination:'disk'});});
test('disk conflict never becomes a false successful browser-only retry',async()=>{let calls=0;const f=fixture(async()=>{calls++;return{ok:false,status:409};});f.profiles.serverAvailable=true;await assert.rejects(persistOriginalProfile(f.profiles,f.save),/changed in another window/);await assert.rejects(persistOriginalProfile(f.profiles,f.save),/changed in another window/);assert.equal(calls,1);});
test('source options default on and persist independently of profile selection',()=>{const f=fixture();assert.deepEqual(readOriginalOptions(f.storage),{music:true,sound:true,damageText:true});const app={save:f.save,profiles:f.profiles,hasProfile:false,store(){}};installOriginalOptions(app);app.applyOriginalSettings();app.persistOriginalSettings('music',false);app.persistOriginalSettings('sound',true);assert.deepEqual(readOriginalOptions(f.storage),{music:false,sound:true,damageText:true});app.save=newSave(data,4);app.applyOriginalSettings();assert.equal(app.save.settings.music,false);assert.equal(app.save.settings.sound,true);assert.equal(app.save.settings.speed,1);});
test('source options migrate existing profile preferences and tolerate malformed device settings',()=>{const f=fixture();f.storage.setItem(ORIGINAL_OPTIONS_KEY,'not json');assert.deepEqual(readOriginalOptions(f.storage,{music:false,sound:true,damageText:false}),{music:false,sound:true,damageText:false});writeOriginalOptions(f.storage,{music:true,sound:false,damageText:true});assert.deepEqual(readOriginalOptions(f.storage,{music:false,sound:true,damageText:false}),{music:true,sound:false,damageText:true});});

test('source global options immediately update a temporary challenge or multiplayer battle',()=>{for(const mode of ['challenge','multiplayer']){const f=fixture(),temporary=newSave(data,4),app={save:f.save,profiles:f.profiles,hasProfile:true,battle:{save:temporary,mode},store(){}};installOriginalOptions(app);app.persistOriginalSettings('damageText',false);app.persistOriginalSettings('music',true);assert.equal(temporary.settings.damageText,false,mode);assert.equal(temporary.settings.music,true,mode);assert.equal(f.save.settings.damageText,false,mode);const replacement=newSave(data,7);app.battle={save:replacement,mode};app.applyOriginalSettings();assert.equal(replacement.settings.damageText,false,mode);assert.equal(replacement.settings.music,true,mode);assert.equal(replacement.pokemon[0].speciesId,7);}});
