import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {newSave,makePokemon,validateSave,loadSave,LEGACY_SAVE_KEY,SAVE_VERSION} from '../src/model.js';
import {buyItem,useEvolutionItem,teachMove,tradePokemon,recordOwned} from '../src/profile-features.js';
import {LocalProfiles,redeemGift} from '../src/local-services.js';
import {importLegacySave} from '../src/legacy-import.js';
const data=JSON.parse(fs.readFileSync(new URL('../public/data/game-data.json',import.meta.url)));
const storage=()=>{const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v),m};};
test('v1 saves migrate while retaining the original stored backup',()=>{const save=newSave(data,1);save.version=1;delete save.inventory;const s=storage();s.setItem(LEGACY_SAVE_KEY,JSON.stringify(save));const actual=loadSave(data,s);assert.equal(actual.version,SAVE_VERSION);assert.deepEqual(actual.dex.normal,[1]);assert.equal(JSON.parse(s.getItem(LEGACY_SAVE_KEY)).version,1);});
test('legacy complete count, all nine target modes, items, flags and form dex import',()=>{const input=Array.from({length:9},(_,i)=>({species:25,level:10,move1:5,moveSelected:1,targetType:i+1,myID:i,position:i,tag:'Sparky'}));const {save,warnings}=importLegacySave(input,data,{account:{slots:{1:{advanced:1,classic:1,challenge:2,badges:1,version:2}},inventory:{6:1},extraInfo:{32:1},pokedex:'7'.repeat(151)}});const s=validateSave(save,data);assert.equal(s.unlocked,2);assert.deepEqual(s.completed,[1]);assert.equal(s.gameVersion,2);assert.equal(s.inventory[6],1);assert.equal(s.pokemon[1].target,'fastest');assert.equal(s.pokemon[8].target,'no-candy');assert.equal(s.pokemon[0].nickname,'Sparky');assert.equal(s.dex.shadow.length,151);assert(s.originalExtraInfo.includes(32));assert(!warnings.some(s=>s.includes('uses First')));});
test('shop and stone evolution validate before charging and retain identity',()=>{const s=newSave(data,25);const p=s.pokemon[0];s.money=20000;assert(buyItem(s,3).ok);assert.equal(s.money,10000);assert(!useEvolutionItem(data,s,p,2).ok);assert(useEvolutionItem(data,s,p,3).ok);assert.equal(p.speciesId,26);assert(s.dex.normal.includes(25)&&s.dex.normal.includes(26));assert(!s.inventory[3]);assert.equal(s.party[0],p.uid);});
test('invalid move replacement cannot charge or alter moves',()=>{const s=newSave(data,25);s.money=100000;const p=s.pokemon[0];p.moves=[1,2,3,4];const old=JSON.stringify(s);const id=data.species[25].tmMoveIds.find(id=>!p.moves.includes(id));assert(!teachMove(data,s,p,id,9,'tm').ok);assert.equal(JSON.stringify(s),old);assert(teachMove(data,s,p,id,0,'tm').ok);assert.equal(s.money,90000);});
test('local trades swap both parties, preserve custom names and apply trade evolution once',()=>{const a=newSave(data,64),b=newSave(data,93);a.pokemon[0].nickname='Spoon';const auid=a.party[0],buid=b.party[0];assert(tradePokemon(data,a,auid,b,buid).ok);assert.equal(a.pokemon[0].speciesId,94);assert.equal(b.pokemon[0].speciesId,65);assert.equal(b.pokemon[0].nickname,'Spoon');assert.equal(a.party[0],buid);assert.equal(b.party[0],auid);});
test('profile bank roundtrips all three profiles and trades in a single snapshot',async()=>{const s=storage(),bank=new LocalProfiles(data,s,null);await bank.initialize();bank.create(0,newSave(data,1));bank.create(1,newSave(data,4));bank.select(0);assert(bank.trade(1,bank.current.party[0],bank.bank.slots[1].party[0]).ok);const restored=new LocalProfiles(data,s,null);await restored.initialize();assert.equal(restored.current.pokemon[0].speciesId,4);assert.equal(restored.bank.slots[1].pokemon[0].speciesId,1);});
test('offline gifts enforce progression and one-time claims',()=>{const s=newSave(data,1);assert(redeemGift(data,s,'ptd-local',makePokemon).ok);assert(!redeemGift(data,s,'PTD-LOCAL',makePokemon).ok);assert(!redeemGift(data,s,'SHINY-GEODUDE',makePokemon).ok);s.challengeCompleted=1;assert(redeemGift(data,s,'SHINY-GEODUDE',makePokemon).ok);assert(s.giftsClaimed.includes('challenge-1'));});

test('sparse source party positions normalize to six explicit null-capable slots',()=>{const s=newSave(data,1),uid=s.party[0];s.party[4]=uid;delete s.party[0];assert.deepEqual(validateSave(s,data).party,[null,null,null,null,uid,null]);s.party[0]=uid;assert.throws(()=>validateSave(s,data));});
