import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';
import{storyWinController,STORY_LOST_GRAPHICS}from'../src/story-data-stage.js';
import{StoryRuntime,StoryClip}from'../src/story-runtime.js';import{newSave,makePokemon}from'../src/model.js';
const json=p=>JSON.parse(readFileSync(new URL(p,import.meta.url)));const data=json('../public/data/game-data.json'),timelines=json('../public/data/story-timelines.json'),levelData=json('../public/data/levels.json');
const stage=id=>[...levelData.levels,...levelData.variants].find(l=>l.id===id);
function runtime(id,save=newSave(data,1),opts={}){return new StoryRuntime(data,{timelines,save,level:stage(id),...opts});}
function traverse(rt,{choice='no',direction='left',limit=10000}={}){for(let f=0;f<limit&&!rt.closed;f++){rt.tick();if(f%5)continue;const cs=rt.controls;let c=cs.find(c=>/^butt_(next|end|start|close)$/.test(c.name))??cs.find(c=>c.name===`butt_${choice}`)??cs.find(c=>/^btn_(left|right|up|down|end)$/.test(c.name));if(c)rt.click(c.clip);}return rt;}

test('all source MovieClip timelines initialize and preserve source stop/loop actions',()=>{for(const id of Object.keys(timelines.symbols)){const clock={frame:0};const c=new StoryClip(timelines,Number(id),{clock});for(let i=0;i<3;i++){clock.frame++;c.tick();}assert.ok(c.currentFrame>=1&&c.currentFrame<=c.totalFrames,String(id));}assert.equal(timelines.unparsedActions.length,0);});
test('every campaign and variant intro/win reaches its original transition without Skip',()=>{let count=0;for(const level of [...levelData.levels,...levelData.variants])for(const key of ['introPopup','winPopup']){const name=key==='winPopup'?storyWinController(level):level[key];if(!name)continue;const save=newSave(data,1);save.unlocked=typeof level.id==='number'?level.id:17;const rt=new StoryRuntime(data,{timelines,save,level}).open(name);traverse(rt);assert.equal(rt.closed,true,`${level.id} ${name}: ${rt.root?.currentLabel} ${rt.controls.map(c=>c.name)}`);count++;}assert.ok(count>=136);});
test('first visit source intro prevents Skip and closing records the attempted stage',()=>{const save=newSave(data,1);save.unlocked=12;const rt=runtime(12,save).open(stage(12).introPopup);assert.equal(rt.controls.some(c=>c.name==='butt_skip'),false);traverse(rt);assert.equal(save.lastLevelVisited,12);});
test('ending trade modifies the first party Slowbro identity and preserves its appearance',()=>{const save=newSave(data,1);const slowbro=makePokemon(data,80,55,{shiny:1,nickname:'Buddy'});save.pokemon.push(slowbro);save.party=[slowbro.uid];save.unlocked=37;const rt=runtime(36,save).open('class_1041');traverse(rt,{choice:'yes'});assert.equal(rt.closed,true);assert.equal(save.pokemon.find(p=>p.uid===slowbro.uid),slowbro);assert.equal(slowbro.speciesId,108);assert.equal(slowbro.level,1);assert.deepEqual(slowbro.moves,[119]);assert.equal(slowbro.selectedMove,119);assert.equal(slowbro.shiny,1);assert.equal(slowbro.nickname,'Lickitung');assert.equal(save.badges,8);});
test('ending trade ignores Slowbro in storage and accepts the source No branch',()=>{for(const inParty of [false,true]){const save=newSave(data,1),p=makePokemon(data,80,55);save.pokemon.push(p);if(inParty)save.party=[p.uid];const rt=runtime(36,save).open('class_1041');traverse(rt,{choice:'no'});assert.equal(p.speciesId,80);assert.equal(p.level,55);assert.equal(save.badges,8);}});
test('quest flags stay compatible with both existing Rock Tunnel and recovered controllers',()=>{const save=newSave(data,1);save.originalExtraInfo=[8];const p=runtime(17,save).playerProfile;assert.equal(p.haveThisExtraInfo(8),true);assert.equal(p.addExtraInfo(9),true);assert.equal(p.addExtraInfo(9),false);assert.deepEqual(save.originalExtraInfo,[8,9]);assert.equal(save.extraInfoValues[9],1);});
test('temporary challenge party reads and writes do not replace the campaign collection',()=>{const save=newSave(data,1),temporary=newSave(data,4);const r=runtime(1,save,{battle:{save:temporary}});assert.equal(r.playerProfile.partyList[0].num,4);r.playerProfile.partyList[0].level=50;assert.equal(temporary.pokemon[0].level,50);assert.equal(save.pokemon[0].level,5);r.playerProfile.addExtraInfo(20);assert.equal(save.extraInfoValues[20],1);assert.equal(temporary.extraInfoValues[20],undefined);});

test('all recovered defeat dialogs retain their source close behavior',()=>{for(const level of [...levelData.levels,...levelData.variants]){const name=STORY_LOST_GRAPHICS[level.className];if(!name)continue;const rt=new StoryRuntime(data,{timelines,save:newSave(data,1),level});rt.open('class_986',[rt.stage,rt.clip(name)]);traverse(rt);assert.equal(rt.closed,true,level.className);}});
test('original capture popup names its Pokémon and closes through its source end click',()=>{const save=newSave(data,1),p=makePokemon(data,25,7,{shiny:1});const rt=runtime(1,save);rt.open('class_971',[rt.stage,{myProfile:rt.profile(p)}]);for(let i=0;i<100;i++)rt.tick();assert.equal(rt.root.actual.whoCaught.text,'You caught a Pikachu!');assert.equal(rt.root.actual.gfx_poke.currentLabel,'s25');rt.click(rt.root);assert.equal(rt.closed,true);});
test('original evolution timeline reaches its mutation callback and can be stopped',()=>{for(const stop of [false,true]){const save=newSave(data,1),p=save.pokemon[0],rt=runtime(1,save);let evolved=0;rt.stage.check_Learn_Move=()=>{};rt.open('popups_Check_Evolve',[rt.stage,{myProfile:rt.profile(p),evolve(){if(!evolved++){p.speciesId=2;}}}]);for(let i=0;i<500&&!rt.closed;i++){rt.tick();if(stop){const b=rt.controls.find(c=>c.name==='stop_evolving_butt');if(b)rt.click(b.clip);}else if(rt.root.actual?.currentLabel==='done_evolving')rt.click(rt.root);}assert.equal(rt.closed,true);assert.equal(p.speciesId,stop?1:2);assert.equal(evolved,stop?0:1);}});
test('Oak victory controls retain the map-parent translation after its source tween',()=>{const save=newSave(data,1);save.unlocked=43;const rt=runtime(1,save).open('class_976');rt.tick(30);assert.equal(rt.renderRoot.x,100);assert.equal(rt.renderRoot.y,10);const skip=rt.controls.find(c=>c.name==='butt_skip');assert.ok(skip.x>=0&&skip.y>=0);assert.ok(skip.x+skip.width<=800);});
test('source Ready Go finishes on its original end label and starts the prepared wave',()=>{let completion=null;const rt=runtime(1,newSave(data,1),{onComplete:r=>completion=r});rt.open('class_974');assert.deepEqual([rt.root.x,rt.root.y],[400,145]);const end=rt.root.meta.labels.end;assert.ok(end>1);rt.tick(end-2);assert.equal(rt.closed,false);rt.tick();assert.equal(rt.closed,true);assert.equal(completion.type,'start-battle');assert.deepEqual(completion.args,[false]);});
test('source party null slots retain indices and rewards fill the first empty slot',()=>{const save=newSave(data,1),other=makePokemon(data,4,5);save.pokemon.push(other);save.party=[null,save.pokemon[0].uid,null,other.uid,null,null];const rt=runtime(1,save),party=rt.playerProfile.partyList;assert.equal(party[0],null);assert.equal(party.length,6);party[1]=null;assert.equal(save.party[1],null);assert.equal(save.party[3],other.uid);party.push(rt.profile(save.pokemon[0]));assert.equal(save.party[0],save.pokemon[0].uid);assert.equal(save.party[3],other.uid);assert.equal(party.length,6);});
test('replacing the selected source move keeps the selected slot',()=>{const save=newSave(data,1),p=save.pokemon[0];p.moves=[1,2,3,4];p.selectedMove=3;const profile=runtime(1,save).profile(p);profile.move3=5;assert.equal(p.selectedMove,5);assert.equal(profile.moveSelected,3);profile.move1=6;assert.equal(p.selectedMove,5);assert.equal(profile.moveSelected,3);});
test('map-parent endings preserve the current source zoom through their camera movement',()=>{for(const [id,name,end]of [[1,'class_976',[100,10]],[2,'class_1066',[0,0]],[3,'class_1005',[0,0]]]){const save=newSave(data,1);save.unlocked=43;const rt=runtime(id,save);Object.assign(rt.stage.gfx_BG,{x:-70,y:-35,scaleX:.5,scaleY:.5});rt.open(name);rt.tick(22);assert.deepEqual(rt.renderRoot.renderMatrix,[.5,0,0,.5,...end],name);const root=rt.root,local=root.controls(),global=rt.controls;assert.ok(global.length,name);for(const hit of global){const own=local.find(c=>c.name===hit.name);assert.ok(own,hit.name);assert.ok(Math.abs(hit.x-(end[0]+own.x*.5))<.001,`${name} ${hit.name} x`);assert.ok(Math.abs(hit.y-(end[1]+own.y*.5))<.001,`${name} ${hit.name} y`);assert.ok(Math.abs(hit.width-own.width*.5)<.001,`${name} ${hit.name} width`);}}});

test('Rock Tunnel encounter selection uses the supplied RNG without replacing global randomness',()=>{
 const original=Math.random;const external=()=>.99;Math.random=external;
 try {
   const rt=runtime('class_954',newSave(data,1),{rng:()=>.1});rt.open('class_985');traverse(rt);
   assert.equal(rt.controller.var_87,41,'the injected 10% draw selects Zubat');
   assert.equal(Math.random,external);
 }finally{Math.random=original;}
});
